
esphome:
  name: "apollo-r-pro-1-eth"
  friendly_name: Apollo R_PRO-1
  comment: Apollo R_PRO-1
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "ApolloAutomation.R-PRO-1-ETH"
    version: ${version}

  min_version: 2024.6.4
  on_boot:
  - priority: -10
    then:
      - if:
          condition:
            - lambda: "return id(runTest);"
          then:
            - lambda: "id(testScript).execute();"
  
dashboard_import:
  package_import_url: github://ApolloAutomation/R_PRO-1/Integrations/ESPHome/R_PRO-1_ETH.yaml
  import_full_config: false

ota:
  - platform: esphome
    id: ota_esphome
  - platform: http_request
    id: ota_managed

http_request:
  verify_ssl: true

safe_mode:

update:
  - platform: http_request
    id: update_http_request
    name: Firmware Update
    source: https://apolloautomation.github.io/R_PRO-1/firmware-e/manifest.json

logger:

ethernet:  
  type: W5500  
  clk_pin: GPIO10  
  mosi_pin: GPIO12 
  miso_pin: GPIO11
  cs_pin: GPIO9
  interrupt_pin: GPIO13
  reset_pin: GPIO14

select:
  - platform: template
    id: firmware_selector
    name: Firmware Type
    icon: "mdi:test-tube"
    entity_category: config
    optimistic: true
    restore_value: true
    options:
      - "WiFi"
      - "Ethernet"
    initial_option: "Ethernet"
    on_value:
      then:
        - if:
            condition:
              lambda: 'return id(firmware_selector).state == "Ethernet";'
            then:
              - logger.log: "OTA updates set to use ethernet firmware"
              - lambda: id(update_http_request).set_source_url("https://apolloautomation.github.io/R_PRO-1/firmware-e/manifest.json");
              - component.update: update_http_request
            else:
              - logger.log: "OTA updates set to use wifi firmware"
              - lambda: id(update_http_request).set_source_url("https://apolloautomation.github.io/R_PRO-1/firmware-w/manifest.json");
              - component.update: update_http_request

packages:
  core: !include Core.yaml
